pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/jay-java/bootaws/tree/master/BootJSP.git'
            }
        }
        stage('Build WAR') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t BootJSP:latest .'
            }
        }
        stage('Run Container') {
            steps {
                sh '''
                docker rm -f BootJSP || true
                docker run -d --name BootJSP -p 9090:9090 BootJSP:latest
                '''
            }
        }
    }
}
